source 'https://github.com/CocoaPods/Specs.git'        #官方仓库地址
source 'https://github.com/aidongsheng/adsSpecs.git'        #私有仓库地址

target 'ZJDCIndexControllerModule_Example' do
  pod 'ZJDCIndexControllerModule', :path => '../'

  pod 'adsCoreKit'
end
